version: '3.8'

services:
  trinitychatbot:
    build: 
      context: .
      dockerfile: dockerfile
    container_name: trinitychatbot
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - trinity-network
    init: true

networks:
  trinity-network:
    driver: bridge